version: 2
updates:
  - package-ecosystem: "npm" # Change this to "maven", "gradle", "gomod", etc., as needed
    directory: "/" # Root directory of your project
    schedule:
      interval: "daily" # Change this to "daily" or "monthly" as required
    open-pull-requests-limit: 4
    allow:
      - dependency-type: "direct"
    security-updates: true
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"] # Ignores major version updates
    commit-message:
      prefix: "chore"
      include: "scope"
