version: 2
updates:
  - package-ecosystem: "npm" # Change this to "maven", "gradle", "gomod", etc., as needed
    directory: "/" # Root directory of your project
    schedule:
      interval: "daily" # Change this to "daily" or "monthly" as required
    target-branch: "UAT"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
        update-type: "security"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependabot-open"
      - "dependencies"
