version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"  # Adjust if your package.json is in a subdirectory
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
        update-type: "version-update:semver-minor"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
