name: Snyk Security

on:
  push:
    branches: ["master" ]
  pull_request:
    branches: ["master"]


jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: snyk/actions/setup@master
      - name: Snyk Code Test
        continue-on-error: true
        run: snyk code test 
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Get JSON data
        run: cat snykResult.json
